### PR TITLE
update-bridge

### PR DESCRIPTION
**Pull request by crow**
Bridge version bump to indicate an update to the Gimbal SDK to 3.1.1.

### CODE REVIEW

**Comment by rlepinski** [comment]
👍

**Comment by marc-scig** [comment]
💛

**Comment by BrianBatchelder** [comment]
:thumbsup:, but why did it need to be updated? Nothing seems to have changed except its own version number.

**Comment by crow** [comment]
The gimbal dependency will pull in whatever is currently in master at the repo. When the master branch in the gimbal dependency repo changes, we need to bump the version to indicate this change.

**Pull request merged**
