### PR TITLE
Added android support to cordova-gimbal-bridge

### PR DESCRIPTION
**Pull request by koga73**
Added support for Android.
Lifted GimbalAdapter from the UA-extensions repo
Added GimbalAdapterService for persistence when the app is in background / closed
Created a JavaScript API for both platforms with the ability to start / stop monitoring
Updated documentation

### CODE REVIEW

**Comment by rlepinski** [comment]
Looks pretty good. Some of the files have inconsistent spacing (tabs vs spaces) and code style (`if (` vs `if(`). We need to get it fixed before we merge. Let me know if you need some help with that.

**Comment by koga73** [comment]
Tweaked the code a bit and updated formatting for better consistency

**Comment by koga73** [comment]
I believe this is ready to be merged now

**Comment by rlepinski** [comment]
@koga73 We are working on a few more changes for the cordova-urbanairship plugin. After we release it ill merge and release this PR. Thanks for all the work!

**Comment by rlepinski** [comment]
@koga73 Everything is released, Thanks again for your help!

**Pull request merged**
